### ISSUE TITLE
Are ye ready scrubs?

### ISSUE THREAD

**Issue by qx-775** [sykeben/Spongebuntu#1]
Hi! What a great initiative. I want you to know that together we can make spongebuntu a dream come true!

We should make some good design choices though:

- What Window Manager or Desktop Environment will SB contain? Will it be available with multiple flavours or will 1 DE/WM supported - i.e like Kubuntu or Xubuntu or Lubuntu does.
- Personally I like the idea of i3wm since there's no officially supported i3wm ubuntu flavour. But if you don't want to get canonicals vote then do whatever.

- I think a good usable booting/shutdown theme should be applied, with a hacked plymouth
A startup image/video  (with music ofcourse) would something like this:
https://www.youtube.com/watch?v=r9L4AseD-aA

And the shutdown image (with music ofcourse) would look something like this:
https://www.youtube.com/watch?v=MiKuhfDjims

- Each virtual desktop has it's own area, virtual desktop is spongebob's pineapple, whereas virtual desktop 2 is the Krusty Krab.

- Every 1 hour the screen will get autolocked with an image of plankton trying to steal the secret Krusty Krab recipe.

- Different live wallpapers (with the livewallpaper software) will randomly be shown as the wallpaper, each containing SpongeBob items though. Gary the Snail walking/snailing through the screen and so on. I think I could do that.

- Patrick or plankton  will show up on the screen randomly doing patrick/plankton stuff like M$ Word clippy does:
https://davescomputertips.com/wp-content/uploads/2014/05/clippy-with-text.jpg

- The  loading animation on the mouse shows patrick doing 360 degree rolls. Since patrick is so slow and loading a program is slow too. But a reddit user had also the idea of using the gear icon as a button

What ya like of the ideas?

BRB Rewatching SpongeBob from the start

**Comment by incrazyboyy** [comment]
Great ideas here! I also have two additional ones:

- Complete custom spongebob icon theme

- Plankton should show up in the terminal just like this Clippy example here:
https://gist.github.com/Raimondi/e1db9a30589639685ee8

**Comment by sykeben** [comment]
The project is dead sadly, as I have no time to develop this due to school and robotics build season. Anyone is welcome to take over though. I am willing to allow more people to commit to this repo, if they are worthy.
